# Generated by Django 4.2.30 on 2026-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContabilidadPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permisos_Contabilidad',
                'verbose_name_plural': 'Permisos_Contabilidad',
                'permissions': [('modulo_contabilidad', 'modulo_contabilidad'), ('modulo_contabilidad_dl', 'modulo_contabilidad_dl'), ('modulo_contabilidad_cv', 'modulo_contabilidad_cv'), ('modulo_contabilidad_ajs', 'modulo_contabilidad_ajs'), ('contabilidad_item', 'contabilidad_item'), ('contabilidad_presupuesto', 'contabilidad_presupuesto'), ('contabilidad_evaluacion_desempeno', 'contabilidad_evaluacion_desempeno'), ('contabilidad_costos', 'contabilidad_costos'), ('ver_reportes_contabilidad', 'Puede ver reportes de contabilidad')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
