# Generated by Django 4.2.30 on 2026-09-03 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boletas', '0007_alter_payrollrelease_id_portalcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_document', models.CharField(db_index=True, max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida')], default='IN', max_length=10)),
                ('source', models.CharField(default='QR', max_length=20)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-marked_at',),
            },
        ),
    ]
