# Generated by Django 4.2.30 on 2026-09-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0011_alter_boletapermission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemark',
            name='source',
            field=models.CharField(default='BARCODE', max_length=20),
        ),
    ]
