# Generated by Django 4.2.30 on 2026-09-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0013_alter_boletapermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletapermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('visualizar_boletas', 'Puede visualizar boletas'), ('gestionar_publicacion_boletas', 'Puede validar y autorizar boletas'), ('ver_marcaciones', 'Puede ver marcaciones'), ('administrar_boletas', 'Puede administrar completamente las boletas')], 'verbose_name': 'Permiso de boletas', 'verbose_name_plural': 'Permisos de boletas'},
        ),
    ]
